version: "3"

networks:
    backend:
        driver: bridge

volumes:
    mysql-database:
        driver: local

    mailcatcher-data:
        driver: local

    ### ignore folder volume #####
    var:
        driver: local
    vendor:
        driver: local
    node_modules:
        driver: local

services:
    ### ECCube4 ##################################
    ec-cube:
        ### ローカルでビルドする場合は以下のコマンドを使用します
        ## docker build -t ec-cube --no-cache --pull --build-arg TAG=8.1-apache .
        ## docker tag ec-cube ghcr.io/ec-cube/ec-cube-php:8.1-apache
        build: .
        ports:
            - 8080:80
            - 4430:443
        volumes:
            ### 同期対象からコストの重いフォルダを除外 #####################
            - ".:/var/www/html"
        environment:
            # EC-CUBE environments
            APP_ENV: "dev"
            APP_DEBUG: 1
            MAILER_DSN: "smtp://mailcatcher:1025"
            ECCUBE_AUTH_MAGIC: "<change.me>"
            DATABASE_URL: "mysql://dbuser:secret@mysql/eccubedb"
            DATABASE_SERVER_VERSION: 5.7
            DATABASE_CHARSET: 'utf8mb4'
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
    ### Mailcatcher ##################################
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
            - backend
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-database:/var/lib/mysql
            - ./dockerbuild/grant_to_dbuser.sql:/docker-entrypoint-initdb.d/grant_to_dbuser.sql
        ports:
            - 13306:3306
        networks:
            - backend
        healthcheck:
            test: mysqladmin ping
            interval: 3s
            timeout: 3s
            retries: 3
